### ISSUE TITLE
Tool in the Crafting Table crash

### ISSUE THREAD

**Issue by Yulife** [mekanism/Mekanism#1913]
As soon as you put a tool from Mekanism in a crafting table to, for example, craft a paxel you crash and get this log: http://paste.ee/p/Mz4Yj
Latest Mekanism, Forge 1225

**Comment by GotoLink** [comment]
Has been determined to be Mekanism issue, roughly it register items in FMLInit stage instead of FMLPreInit. Which is too late and can cause a wide variety of issues.
It is only coincidental that some mods would reveal the problem, due to the complexity of mod loading order.

**Comment by unpairedbracket** [comment]
Thanks @GotoLink, that's very helpful. Presuming moving the registration doesn't cause any unforeseen issues, you can expect a fix soon. Presuming the buildserver has been fixed in the last week or so, yo can expect a new build soon too. (Sorry it's taken so long)

**Comment by AnonymousPuppy** [comment]
Awesome! Looking forward to a fix soon, so I can update my modpack :)

**Comment by AnonymousPuppy** [comment]
Has a fix been released?

**Comment by Cealian** [comment]
Is this problem solved? I am using the lastest Mekanism and are still crashing with mek tools and projectRed tools in my crafting table, crashlogs:
Pred: http://pastebin.com/hQ66WMvV
Mekanism: http://pastebin.com/ZyfBnQ9D

**Comment by Darkmega18** [comment]
Well I do have mine and blade, but it is still blowing up. :V awkward that every other tool in my pack doesn't blow up, yet mekanism's do. >_>

**Comment by Yulife** [comment]
It's Project Red, not Redpower.

**Comment by Darkmega18** [comment]
same thing. I keep calling it redpower cause thats what it's based off. and since you've already seen the fail I can't be bothered editing it. :V

**Comment by Sunconure11** [comment]
Any issues with blood magic in the related error from the blood magic github? It appears it may be connected to a crash involving compression sigils.

**Comment by Darkmega18** [comment]
The plot thickens... and I've never noticed any blood magic derps. Other than a rendering glitch when stuff is in the altar, but that's only visual. Nothing crash worthy...
