### ISSUE TITLE
[enhancement] cardbord drop/throw speed is too high

### ISSUE THREAD

**Issue by rapus95** [mekanism/Mekanism#3806]
It'd be nice if the max thrown speed of dropping cardbord boxes could be capped a little lower. Currently it often flys more than 5 blocks away
also:
is there a way to catch&consume the open gui event? (thus not opening the gui in the same click in which i unwrapped the box)
and:
is it intended that one needs both hands free to unwrap the box?

edit:
it seems that most of your machines & blocks fly way too fast when dropping

**Comment by thommy101** [comment]
Just checked the drop code. Its more or less the same as Minecraft itself.
The motion added to the block are exactly the same (Mekanism doesn't overwrite the values).
The drop position is a little bit different. In Minecraft the position is offset on x, y and z with a value between .25 and .75. Mekanism has an offset between .15 and .5.

The unboxing and opening with the same click isn't there anymore, probably fixed by Forge or somewhere in Mekanism.

**Comment by rapus95** [comment]
just an idea from a minecraft coding noob: is it possible that the entity spawn happens while the block still exists, thus all items spawn inside its previous block and thus being launched at higher velocity? If so, why not using the minecraft values since they seem to not have those problems?

Another idea: when shift+wrenching items what about directly placing them into the players inventory and only drop it to the world if there's no space for it in the inventory. Is that possible? From the logical view: when i use a wrench to disassemble a machine i'll be able to do that safely without having a risk of dropping a pump into lava for example. (which is the reason why i'm that feared of the drop speed)

**Comment by pupnewfster** [comment]
The fact of how they drop/fly off will probably be fixed by #5384 as that will have the drop code directly using vanilla's drop code.
