### ISSUE TITLE
Advanced solar panel model issue

### ISSUE THREAD

**Issue by PenguinTech-official** [mekanism/Mekanism#7932]
### Issue description

Advanced solar panel in Mekanism: Generators had an issue with its model .When I place it, it's  one block below the actual bounding box.

### Steps to reproduce

Check the model

### Minecraft version

1.20.1 (Latest)

### (Neo)Forge version

47.2.0

### Mekanism version

10.4.5 (Latest)

**Comment by thiakil** [comment]
screenshots?

**Comment by pupnewfster** [comment]
Sounds like some mod is breaking the `ModifyBakingResult` event potentially rubidium/embeddium. Though maybe we should at some point just add more custom model loaders and do the few conversions we have to via those. (I have moved some already, but there are still three or four using the older way, one of which being the advanced solar panel)

**Comment by PenguinTech-official** [comment]
> screenshots?

https://drive.google.com/file/d/1r7uDvdJvrk0UHNQRJ2pLZkdG9lmNaaaG/view?usp=drive_link

**Comment by PenguinTech-official** [comment]
> screenshots?

![Issue](https://github.com/mekanism/Mekanism/assets/76718866/80a831c3-33e8-403a-b407-bdecd8a03950)

**Comment by PenguinTech-official** [comment]
> Sounds like some mod is breaking the `ModifyBakingResult` event potentially rubidium/embeddium. Though maybe we should at some point just add more custom model loaders and do the few conversions we have to via those. (I have moved some already, but there are still three or four using the older way, one of which being the advanced solar panel)

Ok, I understood, Is there anything i need to do like downgrading mod version or something.

**Comment by thiakil** [comment]
Remove other mods (start with performance mods) until it stops. It works fine with just Mekanism

**Comment by PenguinTech-official** [comment]
> Remove other mods (start with performance mods) until it stops. It works fine with just Mekanism

Ok, I will try

**Comment by PenguinTech-official** [comment]
I have tested it. But the issue is there I tried installing Mekanism, Generators and tool without any mod and I tested with rubidium, embeddium and optifine the issue is there.
Then I installed purebdcraft resource pack with Mekanism addon pack the issue is fixed only when using resource packs.

**Comment by thiakil** [comment]
Can you try it with neoforge?
If it only happens with minecraft Forge, it's a bug on their side

**Comment by PenguinTech-official** [comment]
> Can you try it with neoforge? If it only happens with minecraft Forge, it's a bug on their side

It's okay it's currently fixed with the help of that resource pack

**Comment by inmourning** [comment]
this is still broken on neoforge btw

**Comment by thiakil** [comment]
Please provide full details of your modded environment

**Comment by Alstin112** [comment]
This bug still happens for me
![image](https://github.com/user-attachments/assets/63554496-0a65-4f19-a456-025411e19c06)
my minecraft is
![image](https://github.com/user-attachments/assets/152d6794-17ab-4ea3-846a-a12e6500bcff)
What seems strange to me is that for my friend, using the same mods, this doesn't happen. If you want some of my PC specs, I can provide them.
